backend:
  name: git-gateway
  branch: main
media_folder: "src/assets/stories"
public_folder: "/assets/stories"
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/story"
    create: true
    slug: "{{slug}}"
    fields: 
      - { label: "Title" , name: "title" , widget: "string" }
      - { label: "Description" , name: "description" , widget: "string" }
      - { label: "URL" , name: "url" , widget: "string" }
      - { label: "Tags" , name: "tags" , widget: "list" , default: ["story"] }
      - { label: "Body" , name: "body" , widget: "markdown" }